### ISSUE TITLE
Question / Execute Script

### ISSUE THREAD

**Issue by richardmcameron** [kraten/chessbot#2]
``def highlight_move(driver, user_color, best_move):
    driver.execute_script("""
        chessboard = document.getElementById('game-board');
        x = chessboard.style.width.replace(/\D/g,'') / 8;

        if(arguments[4].localeCompare("white") == 0){
            var from_position_coordinate = [(arguments[0].charCodeAt(0) - 97) * x, (8 - parseInt(arguments[1])) * x];
            var to_position_coordinate = [(arguments[2].charCodeAt(0) - 97) * x, (8 - parseInt(arguments[3])) * x];
        }
        else{
            var from_position_coordinate = [(7 - (arguments[0].charCodeAt(0) - 97)) * x, (parseInt(arguments[1]) - 1) * x];
            var to_position_coordinate = [(7 - (arguments[2].charCodeAt(0) - 97)) * x, (parseInt(arguments[3]) - 1) * x];
        }

        highlight1_pos = arguments[0].charCodeAt() - 'a'.cRFharCodeAt() + 1 
        highlight1_class = '0' + highlight1_pos + '0' + arguments[1];
        element = document.createElement('div');            
        element.setAttribute("id", "highlight1");
        element.setAttribute("class", "square square-" + highlight1_class + " marked-square");        
        element.setAttribute("style", "background-color: rgb(0, 122, 255); opacity: 0.9");    
        chessboard.appendChild(element);

        highlight2_pos = arguments[2].charCodeAt() - 'a'.charCodeAt() + 1
        highlight2_class = '0' + highlight2_pos + '0' + arguments[3];
        element = document.createElement('div');
        element.setAttribute("id", "highlight2");            
        element.setAttribute("class", "square square-" + highlight2_class + " marked-square");        

        element.setAttribute("style", "background-color: rgb(0, 122, 255); opacity: 0.9");    
        chessboard.appendChild(element);
       """, best_move[0], best_move[1], best_move[2], best_move[3], user_color)
    return``

I've been trying to break this block down and read it through but I am having some trouble. This is somewhat of the work horse of the script as you create the element and move the piece to the location. I am trying to implement something similar on lichess but I can quite wrap my head around it. Specifically with the regular expression you are using for x.

**Comment by kraten** [comment]
I will break down this function for you:

`def highlight_move(driver, user_color, best_move)`
> It takes 3 arguments: 
> 1. driver: selenium web driver
> 2. user_color: string which could have two values: white or black
> 3. best_move: string which contains the co-ordinates of squares from where to move the piece to which square. For eg: 'e2e4'


`driver.execute_script()`
> This will execute the JavaScript code passed to it as an argument. Here, I am passing 5 arguments to this JavaScript code: 
> 1. best_move[0]
> 1. best_move[0]
> 1. best_move[0]

The value I got from reading the width of chessboard is something like this `640px`.

`x = chessboard.style.width.replace(/\D/g,'') / 8;`
This regex just removes the non digits part from the string, just leaving behind the number i.e. `x = 640`

**Comment by kraten** [comment]
I will break down this function for you:
&nbsp;

`def highlight_move(driver, user_color, best_move)`

> It takes 3 arguments:
> 1. driver: selenium web driver
> 2. user_color: string which could have two values: white or black
> 3. best_move: string which specifies to move piece from which square to which square. For eg: 'b1c3'

&nbsp;
`driver.execute_script()`

> This will execute the JavaScript code passed to it as an argument. Here, I am passing 5 arguments to this JavaScript code: [best_move[0], best_move[1], best_move[2], best_move[3], user_color]. For eg: ['b','1','c','3','white']    

&nbsp;
```
x = chessboard.style.width.replace(/\D/g,'') / 8;
if(arguments[4].localeCompare("white") == 0){
    var from_position_coordinate = [(arguments[0].charCodeAt(0) - 97) * x, (8 - parseInt(arguments[1])) * x];
    var to_position_coordinate = [(arguments[2].charCodeAt(0) - 97) * x, (8 - parseInt(arguments[3])) * x];
} else {
    var from_position_coordinate = [(7 - (arguments[0].charCodeAt(0)-97)) * x, (parseInt(arguments[1])-1) * x];
    var to_position_coordinate = [(7 - (arguments[2].charCodeAt(0)-97)) * x, (parseInt(arguments[3])-1) * x];
}
```
> You can ignore this above block of code. Looks like, I forgot to remove it. Earlier, I was using the different approach to determine the location of the best move squares based on the board size and then simulating the click event.

&nbsp;
```
highlight1_pos = arguments[0].charCodeAt() - 'a'.charCodeAt() + 1 
highlight1_class = '0' + highlight1_pos + '0' + arguments[1];
element = document.createElement('div');            
element.setAttribute("id", "highlight1");
element.setAttribute("class", "square square-" + highlight1_class + " marked-square");        
element.setAttribute("style", "background-color: rgb(244, 42, 50); opacity: 0.9");    
chessboard.appendChild(element);
```
> In chess.com, every square on the board have a unique class name like the b1 square have a class name 'square-0201'. Here, 02 specifies the B column and 01 specifies the 1st row. Using this logic, I have created the class name of the squares, I want to highlight. To highlight the c3 square, the class name would be 'square-0303'. Once, I got the class name, I created a new div element with this class name and id 'highlight-1' and also added styles to highlight it. Later, I am using this 'highlight-1' id to find this square and click on it.

&nbsp;
I hope you are able to understand it now :)

**Comment by kraten** [comment]
I have removed the redundant code in this commit: 1305dc356fb7de4dbf6db4f5679744048f776cc0
